name: CI/CD Trustclaim Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: master
  cancel-in-progress: true

jobs:


  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.PUBLIC_IP }}
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END
      - name: Pull and Deploy Changes
        run: |
          ssh target "cd /data/trust_claim_backend && git pull origin master && npm i  && npm audit fix --force && npx prisma generate && npx prisma migrate deploy && npm run build && sudo sudo systemctl restart nginx"
