# .github/workflows/ci-cd-pipeline.yml

name: CI/CD Trustclaim Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Git pull and deploy
        env:
          PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USERNAME }}@${{ secrets.PUBLIC_IP }} << 'EOF'
            cd ${WORKSPACE}
            git pull
            bash deploy.sh
