# .github/workflows/ci-cd-pipeline.yml

name: CI/CD Trustclaim Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: master
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.PUBLIC_IP }}
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host target\n  HostName $SSH_HOST\n  User $SSH_USER\n  IdentityFile ~/.ssh/id_rsa\n  LogLevel ERROR\n  StrictHostKeyChecking no" > ~/.ssh/config
          
          # Debug: Print the SSH config to verify its contents
          cat ~/.ssh/config

      - name: Pull and Deploy Changes
        run: |
          ssh target "cd /data/trust_claim_backend && git pull origin master && npm i && npm audit fix --force && npx prisma generate && npx prisma migrate deploy && npm run build && sudo systemctl restart nginx"
