# .github/workflows/ci-cd-pipeline.yml

name: CI/CD Trustclaim Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git pull
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY  }}
          PUBLIC_IP: ${{ secrets.PUBLIC_IP  }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME  }}
        run: |
          pwd
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${SERVER_USERNAME}@${PUBLIC_IP} 
          cd ${WORKSPACE} && cd /data/trust_claim_backend && bash deploy.sh
