# .github/workflows/ci-cd-pipeline.yml

name: CI/CD Trustclaim Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Debug environment variables
        run: |
          echo "PRIVATE_KEY is set: ${PRIVATE_KEY:+yes}"
          echo "PUBLIC_IP is set: ${PUBLIC_IP:+yes}"
          echo "SERVER_USERNAME is set: ${SERVER_USERNAME:+yes}"

      - name: Git pull
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          pwd
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -vvv -o StrictHostKeyChecking=no -i private_key ${SERVER_USERNAME}@${PUBLIC_IP} << 'EOF'
            cd ${WORKSPACE} && bash deploy.sh
