# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x,20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: BUSINESS LOGIC
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm audit fix --force
    - run: npm run build --if-present
  

  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: SSH SETUP
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        ENV: ${{ secrets.ENV }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${SERVER_USERNAME}@${PUBLIC_IP}
          set -e
          WORKSPACE=/data/trust_claim_backend
          if [ ! -d "$WORKSPACE" ]; then
            echo "Directory $WORKSPACE does not exist. Creating it..."
            mkdir -p $WORKSPACE
          fi
          cd $WORKSPACE
          if [ ! -d ".git" ]; then
            git clone https://github.com/Whats-Cookin/trust_claim_backend.git .
          else
            git pull origin master
          fi
          touch .env
          echo "${ENV}" > .env
          bash deploy.sh
